# ==============================================================================
# @file       FUNDING.yml
# @brief      Configuración de patrocinio/donaciones oficial de GitHub
# @author     Luis Zambrano Gahón (ignot)
# ==============================================================================

# github: [ignot-win]
# ko_fi: ignot
# patreon: ignot
custom: ["https://paypal.me/lzambranogahon?locale.x=es_XC&country.x=EC"]